return {
  {
    "nvim-treesitter/nvim-treesitter-textobjects",
  },

  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      local config = require("nvim-treesitter.configs")

      config.setup({
        ensure_installed = {
          "awk",
          "bash",
          "bibtex",
          "c",
          "cmake",
          "comment",
          "cpp",
          "css",
          "csv",
          "cuda",
          "diff",
          "dockerfile",
          "doxygen",
          "editorconfig",
          "gitcommit",
          "gitignore",
          "go",
          "gomod",
          "gosum",
          "gotmpl",
          "gowork",
          "graphql",
          "groovy",
          "hcl",
          "helm",
          "html",
          "java",
          "javadoc",
          "javascript",
          "jq",
          "json",
          "json5",
          "llvm",
          "lua",
          "luadoc",
          "make",
          "markdown",
          "markdown_inline",
          "nginx",
          "php",
          "phpdoc",
          "python",
          "regex",
          "rust",
          "sql",
          "terraform",
          "twig",
          "vim",
          "vimdoc",
          "xml",
          "yaml",
        },
        auto_install = true,
        highlight = { enable = true },
        indent = { enable = true },
        incremental_selection = { enable = true },
      })
    end
  }
}
